#!/bin/bash

usage() {
	if (( $# > 0 )); then
		echo '               _     _ '
		echo '__      ____ _| |_  | |'
		echo '\ \ /\ / / _` | __| | |'
		echo ' \ V  V / (_| | |_  |_|'
		echo '  \_/\_/ \__,_|\__| (_)'
		echo
		echo "$@"
		echo
	fi

	echo "makeitso: build tool"
	echo ""
	echo "usage: makeitso [options]"
	echo " -t (or --tag):         container tag"
	echo " -c (or --compile):     compile things. yes or no"
	echo " -b (or --build):       build containers. yes or no"
	echo " -p (or --push):        push containers to namespaces. yes or no"
	echo " -n (or --namespace):   namespace for containers, eg: quay.io/cgilmour/"
}

error() {
	echo
	echo '       _                             _ ' 
	echo '  ___ | |__  _ __   ___   ___  ___  | |'
	echo ' / _ \|  _ \|  _ \ / _ \ / _ \/ __| | |'
	echo '| (_) | | | | | | | (_) |  __/\__ \ |_|'
	echo ' \___/|_| |_|_| |_|\___/ \___||___/ (_)'
	echo
	echo "$@"
	echo
}

fatal() {
	error "$@"
	exit 1
}

log() {
	if (( $# < 2 )); then
		error "log(): insufficient parameters" "$@"
		exit
	fi
	local target=$1 state=$2
	shift 2
	if (( $# > 0 )); then
		printf "%s:%s:%s\n" "$target" "$state" "$(printf " %s" "$@")"
	else
		printf "%s:%s\n" "$target" "$state"
	fi
}


if ! cd "${0%/*}"; then
	error "Error attempting to cd to installation directory."
	exit 1
fi

# Common shopt's
shopt -s nullglob

# Parse command-line options
tag=unspecified
compile=maybe
build=maybe
push=maybe
namespaces=()

acceptable_tag() {
	if (($# != 1)); then
		fatal "acceptable_tag(): expected 1 parameter, got $#"
	fi
	if ! [[ "$1" ]]; then
		echo "tag empty"
		return 1
	fi
	if ((${#1} > 128)); then
		echo "tag too long"
		return 1
	fi
	if [[ "${1:0:1}" != [A-Za-z0-9] ]]; then
		echo "first character must be uppercase/lowercase letter or a digit"
		return 1
	fi
	if [[ "${1//[A-Za-z0-9._-]/}" ]]; then
		echo "tag can only contain uppercase/lowercase letters, digits, underscore, period or dash"
		return 1
	fi
}

yes_no_maybe() {
	if (($# != 1)); then
		fatal "yes_no_maybe(): expected 1 paramter, got $#"
	fi
	case "$1" in 
	yes|no|maybe)
		return 0
		;;
	*)
		return 42
		;;
	esac
}

while [[ $1 == -* ]]; do
	if [[ $1 == -*=* ]]; then
		set -- "${1%%=*}" "${1#*=}" "${@:2}"
	fi
	case "$1" in
	-h|--help)
		usage
		exit 0
		;;
	-t|--tag)
		tag="$2"
		shift 2
		;;
	-c|--compile)
		if ! yes_no_maybe "$2"; then
			usage "$1: $2 is not valid"
			exit 1
		fi
		compile="$2"
		shift 2
		;;
	-b|--build)
		if ! yes_no_maybe "$2"; then
			usage "$1: $2 is not valid"
			exit 1
		fi
		build="$2"
		shift 2
		;;
	-p|--push)
		if ! yes_no_maybe "$2"; then
			usage "$1: $2 is not valid"
			exit 1
		fi
		push="$2"
		shift 2
		;;
	-n|--namespace)
		if ! [[ $2 ]]; then
			usage "$1: '$2' is not valid"
			exit 1
		fi
		namespaces+=( "$2" )
		shift 2
		;;
	*)
		usage "Unrecognized option '$1'"
		exit 1
		;;
esac; done

# Compile 
compile() {
	case "$compile" in
		yes)
			;;
		no)
			log compile skipping
			return
			;;
		maybe)
			compile=yes
			;;
	esac

	log compile ... creating volume paths
	volume_paths=(
		"/var/tmp/k8s-network-scan/volumes/src"
		"/var/tmp/k8s-network-scan/volumes/pkg"
		"/var/tmp/k8s-network-scan/volumes/bin"
	)
	for p in "${volume_paths[@]}"; do
		if ! [[ -d "$p" ]]; then
			if ! mkdir -p "$p"; then
				fatal error creating volume path "$p"
			fi
		fi
	done
	log compile ... running compile stage
	docker_flags=(
		-d
		--rm
		--user "$UID"
	)
	volume_flags=(
		-v /var/tmp/k8s-network-scan/volumes/src:/go/src
		-v /var/tmp/k8s-network-scan/volumes/pkg:/go/pkg
		-v /var/tmp/k8s-network-scan/volumes/bin:/go/bin
		-v "$PWD":/go/src/github.com/cgilmour/k8s-network-scan
		-v "$HOME:$HOME"
		-v /etc/passwd:/etc/passwd
	)
	if ! cid=$(docker run "${docker_flags[@]}" "${volume_flags[@]}" golang:1.10-stretch /bin/sleep infinity); then
		fatal error starting compile container
	fi

	while read -r mainpkg _; do
		if ! srcdir="$(docker exec "$cid" go list -f '{{ .Dir }}' "$mainpkg")"; then
			log error getting source directory for "$mainpkg"
			continue
		fi
		if ! docker exec --env GOBIN="$srcdir" "$cid" go install -i "$mainpkg"; then
			log error compiling "$mainpkg"
			build=no
			continue
		fi
	done < <(docker exec "$cid" go list github.com/cgilmour/k8s-network-scan/cmd/...)

	if ! docker kill "$cid"; then
		fatal error stopping compile container
	fi
	if [[ "$build" = maybe ]]; then
		build=yes
	fi
	log compile end
}

build() {
	case "$build" in
	yes)
		return 0
		;;
	no)
		return 42
		;;
	maybe)
		for n in "${namespaces[@]}"; do
			for i in kns-job kns-pod; do
				if ! image_name=$(image_name "$n" "$i"); then
					fatal "build(): error from image_name()"
				fi
				if [[ $(docker images --format '{{ .Repository }}:{{ .Tag }}' "$image_name") != "$image_name" ]]; then
					build=yes
					return 0
				fi
			done
		done
		build=no
		return 42
	esac
}

image_name() {
	if (($# != 2)); then
		fatal "image_name(): expected 2 parameter, got $#"
	fi
	local n="$1" c="$2" name
	case "${n: -1}" in
	[-/])
		name="$n$c:$tag"
		;;
	*)
		name="$n/$c:$tag"
		;;
	esac
	printf "%s" "$name"
}

docker_build() {
	if (($# != 2)); then
		fatal "build_flags(): expected 2 parameter, got $#"
	fi
	local c="$1" p="$2" flags=()
	for n in "${namespaces[@]}"; do
		if ! image_name=$(image_name "$n" "$c"); then
			fatal "build_flags: error from image_name"
		fi
		flags+=( -t "$image_name" )
	done
	docker build "${flags[@]}" "$p"
}

# Build container
build_container() {
	if (($# != 1)); then
		fatal "build_container(): expected 1 parameter, got $#"
	fi
	local c
	c="$1"
	if ! build; then
		log "container-$c" skipping
		return
	fi
	log "container-$c" start building container for "$c" components
	if ! docker_build "$c" "cmd/$c"; then
		fatal error building "$c" container
	fi
	log "container-$c" end
}

registry() {
	if (($# != 1)); then
		fatal "registry(): expected 1 parameter, got $#"
	fi
	local n="$1"
	IFS=/ read -r prefix _ <<< "$n"
	if [[ "$prefix" == *.* ]] || [[ "$prefix" == *:* ]]; then
		registry="$prefix"
	else
		registry="https://index.docker.io/v1/"
	fi
	printf "%s" "$registry"
}

login_not_required() {
	if (($# != 1)); then
		fatal "login_not_required(): expected 1 parameter, got $#"
	fi
	local n="$1"
	if [[ "$n" = "https://index.docker.io/v1/" ]]; then
		return 1
	fi
	IFS=/ read -r prefix _ <<< "$n"
	if [[ "$prefix" == *:* ]]; then
		# Assume login not required for registries specifying ports
		return 0
	fi
	return 1
}

push() {
	case "$push" in
	yes)
		;;
	no)
		log push skipping
		return
		;;
	maybe)
		if ! build; then
			log push skipping
			return
		fi
		;;
	esac
	if ! (( ${#namespaces[@]} )); then
		log push skipping no targets available
		return
	fi

	for n in "${namespaces[@]}"; do
		if ! registry=$(registry "$n"); then
			log push error getting registry for "$n"
			continue
		fi

		log push start pushing containers to "$registry"
		logged_in=0
		# shellcheck disable=SC2016
		if [[ -f ~/.docker/config.json ]] && [[ "$(jq -r --arg registry "$registry" '.auths[$registry].auth // empty' < ~/.docker/config.json)" ]]; then
			log push ... already logged in
			logged_in=1
		fi
		if login_not_required "$registry"; then
			log push ... login not required
			logged_in=1
		fi
		if ! ((logged_in)); then
			if ! docker login "$registry"; then
				fatal error logging into "$registry"
			fi
		fi
		for i in kns-job kns-pod; do
			log push ... pushing "$i"
			if ! docker push "$(image_name "$n" "$i")"; then
				fatal error pushing "$i" to "$registry"
			fi
			log push ... "$i" pushed
		done
		log push end pushing containers to "$registry"
	done
	log push end
}

# Script body
compile
build_container kns-job
build_container kns-pod
push
